### ISSUE TITLE
if v.rfind("__list__") == 0: AttributeError: 'list' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by NoahVG** [adamhajari/spyre#54]
Hi,

I encountered this error immediately after updating pandas from 0.16.2 to 0.18.1. Are you aware of any changes or deprecation in this update that could affect or conflict with spyre's code? The error code is below:

[15/Jun/2016:13:24:31] ENGINE Started monitor thread 'Autoreloader'.
[15/Jun/2016:13:24:31] ENGINE Started monitor thread '_TimeoutMonitor'.
[15/Jun/2016:13:24:31] ENGINE Serving on http://127.0.0.1:8055
[15/Jun/2016:13:24:31] ENGINE Bus STARTED
127.0.0.1 - - [15/Jun/2016:13:24:31] "GET / HTTP/1.1" 200 478655 "" "Mozilla/5.0                                            (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0"
127.0.0.1 - - [15/Jun/2016:13:24:32] "GET /spinning_wheel HTTP/1.1" 200 2663 "ht                                           tp://localhost:8055/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/201001                                           01 Firefox/46.0"
[15/Jun/2016:13:24:32] HTTP
Traceback (most recent call last):
  File "C:\Users\pbm887\AppData\Local\Continuum\Anaconda\lib\site-packages\cherr                                           ypy_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Users\pbm887\AppData\Local\Continuum\Anaconda\lib\site-packages\cherr                                           ypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Users\pbm887\AppData\Local\Continuum\Anaconda\lib\site-packages\cherr                                           ypy_cpdispatch.py", line 60, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Users\pbm887\AppData\Local\Continuum\Anaconda\lib\site-packages\spyre                                           \server.py", line 184, in plot
    args = self.clean_args(args)
  File "C:\Users\pbm887\AppData\Local\Continuum\Anaconda\lib\site-packages\spyre                                           \server.py", line 270, in clean_args
    if v.rfind("**list**") == 0:
AttributeError: 'list' object has no attribute 'rfind'
[15/Jun/2016:13:24:32] HTTP
Traceback (most recent call last):
  File "C:\Users\pbm887\AppData\Local\Continuum\Anaconda\lib\site-packages\cherr                                           ypy_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Users\pbm887\AppData\Local\Continuum\Anaconda\lib\site-packages\cherr                                           ypy\lib\encoding.py", line 220, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Users\pbm887\AppData\Local\Continuum\Anaconda\lib\site-packages\cherr                                           ypy_cpdispatch.py", line 60, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Users\pbm887\AppData\Local\Continuum\Anaconda\lib\site-packages\spyre                                           \server.py", line 215, in table
    args = self.clean_args(args)
  File "C:\Users\pbm887\AppData\Local\Continuum\Anaconda\lib\site-packages\spyre                                           \server.py", line 270, in clean_args
    if v.rfind("**list**") == 0:
AttributeError: 'list' object has no attribute 'rfind'
[15/Jun/2016:13:24:32] HTTP
Request Headers:
  REFERER: http://localhost:8055/
  HOST: localhost:8055
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: image/png,image/_;q=0.8,_/_;q=0.5
  USER-AGENT: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefo                                           x/46.0
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[15/Jun/2016:13:24:32] HTTP
Request Headers:
  REFERER: http://localhost:8055/
  HOST: localhost:8055
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */_
  USER-AGENT: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefo                                           x/46.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
127.0.0.1 - - [15/Jun/2016:13:24:32] "GET /plot?LineItem1=RB&L-89&LineItem2=RB&L                                           -89&LegalEntity2=COFC&output_id=make_plot& HTTP/1.1" 500 1710 "http://localhost:                                           8055/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0                                           "
127.0.0.1 - - [15/Jun/2016:13:24:32] "GET /table?LineItem1=RB&L-89&LineItem2=RB&                                           L-89&LegalEntity2=COFC&output_id=table_id& HTTP/1.1" 500 1711 "http://localhost:                                           8055/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0                                           "

Best,

Noah

**Comment by adamhajari** [comment]
@NoahVG i'm running with pandas==0.19.0 and can't reproduce. Do you have the latest version of spyre? do you get this error with any of the example apps in the examples dir?
